---
name: "Next version action"
description: "Returns the next semantic release version according to conventional commit messages"
outputs:
  updated:
    description: "Whether the version changed"
    value: ${{ steps.script.outputs.updated }}
  version:
    description: "Next version based on conventional commits since last tagged commit"
    value: ${{ steps.script.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: script
      run: |
        ${{ github.action_path }}/next-version.sh | tee output.txt
        cat output.txt | grep -e updated= -e version= >> "$GITHUB_OUTPUT"
      shell: bash
