---
name: Release pipeline
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Obtain next version
        uses: ./
        with:
          create-release: true
          token: ${{ forge.token }}
